name: "Publish package: @exile-watch / doryani"

on:
  push:
    paths:
      - 'packages/**'
      - '!packages/**/*.md'
    branches:
      - main
  workflow_dispatch:

jobs:
  code-quality-assurance:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    name: Code quality assurance
    steps:
      - uses: exile-watch/doryani/code-quality-assurance@main
        with:
          GH_ACTOR: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  publish-package:
    needs: [code-quality-assurance]
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: exile-watch/doryani/publish-package@main
        with:
          GH_ACTOR: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}